#########################################
#       SERVER
#########################################
server.domain=http://book-shelf.uz

#########################################
#       DATABASE
#########################################
spring.datasource.url=jdbc:postgresql://localhost:5432/DB_BookShelf
spring.datasource.username=bookshelf_owner
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

