#########################################
#       SERVER
#########################################
spring.application.name=BookShelf
spring.profiles.active=local
server.port=8080

#########################################
#       Attach
#########################################
attach.upload.folder=images/
attach.upload.url= http://localhost:${server.port}/attach


#########################################
#       EMAIL
#########################################
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=paragrof_92@mail.ru
spring.mail.password=XJgDdB1XW7dBCe1YA9M5
spring.mail.protocol=smtps

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000

#########################################
#       Flyway
#########################################
spring.flyway.baselineOnMigrate=true
spring.flyway.baselineVersion=0


#########################################
#       LOGGING
#########################################
logging.level.root=INFO
logging.level.com.alobek.bookshelf=DEBUG
logging.pattern.console=%date{dd MMM yyyy; HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %green(%msg%n)
# Loglar yoziladigan fayl nomi va joylashuvi
logging.file.name=logs/app.log
logging.file.max-size=1MB
logging.pattern.rolling-file-name=app-%d{yyyy-MM-dd}.%i.log
logging.file.path=logs/


#########################################
#       BORROW SYSTEM
#########################################
borrow.duration = 5


